module.exports = {
  apps: [
    {
      name: 'heidi-auth',
      script: 'yarn',
      args: 'nest start auth --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/auth-error.log',
      out_file: './logs/pm2/auth-out.log',
      log_file: './logs/pm2/auth-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-users',
      script: 'yarn',
      args: 'nest start users --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/users-error.log',
      out_file: './logs/pm2/users-out.log',
      log_file: './logs/pm2/users-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-city',
      script: 'yarn',
      args: 'nest start city --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/city-error.log',
      out_file: './logs/pm2/city-out.log',
      log_file: './logs/pm2/city-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-core',
      script: 'yarn',
      args: 'nest start core --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/core-error.log',
      out_file: './logs/pm2/core-out.log',
      log_file: './logs/pm2/core-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-notification',
      script: 'yarn',
      args: 'nest start notification --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/notification-error.log',
      out_file: './logs/pm2/notification-out.log',
      log_file: './logs/pm2/notification-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-scheduler',
      script: 'yarn',
      args: 'nest start scheduler --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/scheduler-error.log',
      out_file: './logs/pm2/scheduler-out.log',
      log_file: './logs/pm2/scheduler-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-integration',
      script: 'yarn',
      args: 'nest start integration --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/integration-error.log',
      out_file: './logs/pm2/integration-out.log',
      log_file: './logs/pm2/integration-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'heidi-admin',
      script: 'yarn',
      args: 'nest start admin --watch',
      interpreter: 'none',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2/admin-error.log',
      out_file: './logs/pm2/admin-out.log',
      log_file: './logs/pm2/admin-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
