export enum ErrorCode {
  // General errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',

  // Registration/User errors
  DUPLICATE_USERNAME = 'DUPLICATE_USERNAME',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  REGISTRATION_FIELDS_REQUIRED = 'REGISTRATION_FIELDS_REQUIRED',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',

  // Database errors
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_ERROR = 'DATABASE_CONSTRAINT_ERROR',
  DATABASE_TIMEOUT_ERROR = 'DATABASE_TIMEOUT_ERROR',

  // Verification errors
  VERIFICATION_UNSUPPORTED_TYPE = 'VERIFICATION_UNSUPPORTED_TYPE',
  VERIFICATION_INVALID_IDENTIFIER = 'VERIFICATION_INVALID_IDENTIFIER',
  VERIFICATION_TOKEN_INVALID = 'VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_USED = 'VERIFICATION_TOKEN_USED',
  VERIFICATION_TOKEN_CANCELLED = 'VERIFICATION_TOKEN_CANCELLED',
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',
  VERIFICATION_MAX_ATTEMPTS = 'VERIFICATION_MAX_ATTEMPTS',
  VERIFICATION_CANCEL_VERIFIED = 'VERIFICATION_CANCEL_VERIFIED',
  VERIFICATION_ALREADY_SENT = 'VERIFICATION_ALREADY_SENT',

  // Category/core errors
  CATEGORY_IN_USE = 'CATEGORY_IN_USE',
  CATEGORY_REQUEST_INVALID_STATUS = 'CATEGORY_REQUEST_INVALID_STATUS',
  CITY_ACCESS_DENIED = 'CITY_ACCESS_DENIED',
  CITY_CATEGORY_MAPPING_NOT_FOUND = 'CITY_CATEGORY_MAPPING_NOT_FOUND',

  // Redis/Queue errors
  REDIS_CONNECTION_ERROR = 'REDIS_CONNECTION_ERROR',
  QUEUE_OPERATION_ERROR = 'QUEUE_OPERATION_ERROR',
  JOB_PROCESSING_ERROR = 'JOB_PROCESSING_ERROR',
  JOB_TIMEOUT_ERROR = 'JOB_TIMEOUT_ERROR',

  // Job management errors
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_INVALID_STATE = 'JOB_INVALID_STATE',
  JOB_SCHEDULE_ERROR = 'JOB_SCHEDULE_ERROR',
  JOB_EXECUTION_ERROR = 'JOB_EXECUTION_ERROR',
  CRON_VALIDATION_ERROR = 'CRON_VALIDATION_ERROR',

  // Scraping errors
  SCRAPING_NETWORK_ERROR = 'SCRAPING_NETWORK_ERROR',
  SCRAPING_PARSE_ERROR = 'SCRAPING_PARSE_ERROR',
  SCRAPING_RATE_LIMIT_ERROR = 'SCRAPING_RATE_LIMIT_ERROR',
  SCRAPING_BLOCKED_ERROR = 'SCRAPING_BLOCKED_ERROR',

  // Authentication errors
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  SUPER_ADMIN_REQUIRED = 'SUPER_ADMIN_REQUIRED',
  CITY_ADMIN_OR_SUPER_ADMIN_REQUIRED = 'CITY_ADMIN_OR_SUPER_ADMIN_REQUIRED',

  // Configuration errors
  CONFIG_MISSING_REQUIRED = 'CONFIG_MISSING_REQUIRED',
  CONFIG_INVALID_VALUE = 'CONFIG_INVALID_VALUE',

  // External service errors
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_RATE_LIMIT = 'EXTERNAL_SERVICE_RATE_LIMIT',
}
